# Generated by Django 4.0.3 on 2025-05-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_profile_date_profile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='address',
            field=models.TextField(default='Adres Girilmemiş', max_length=100, verbose_name='Yakın Adresi'),
        ),
    ]
