# Generated by Django 4.0.3 on 2025-05-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_emergencycontact_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='relationship',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Yakınlık Derecesi'),
        ),
    ]
