# Generated by Django 4.0.3 on 2025-05-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta'),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='surname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Yakın Adı'),
        ),
        migrations.AddField(
            model_name='profile',
            name='boy',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Boy(cm)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='engel',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Engel Drumu(varsa)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hasta',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Kronik Hastalık(varsa)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ilac',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Kullandığım İlaçlar(varsa)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='kan',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Kan Grubu'),
        ),
        migrations.AddField(
            model_name='profile',
            name='kilo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Kilo(kg)'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Yakın Adı'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Soyad'),
        ),
    ]
