# Generated by Django 4.0.3 on 2025-05-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_emergencycontact_email_emergencycontact_surname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='profile_images/'),
        ),
    ]
