# Generated by Django 5.2.1 on 2025-05-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_emergencyalert_delete_emergencyreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencyalert',
            name='address',
        ),
        migrations.AlterField(
            model_name='emergencyalert',
            name='message',
            field=models.CharField(default='Acil yardım bildirimi!', max_length=255),
        ),
    ]
