# Generated by Django 5.2.1 on 2025-05-12 10:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_remove_emergencyalert_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencyalert',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='emergencyalert',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='emergencyalert',
            name='message',
        ),
        migrations.RemoveField(
            model_name='emergencyalert',
            name='user',
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.profile'),
        ),
        migrations.AlterField(
            model_name='emergencyalert',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
