# Generated by Django 5.2.1 on 2025-05-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_rename_created_at_emergencyalert_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyalert',
            name='address',
            field=models.CharField(blank=True, null=True),
        ),
    ]
