# Generated by Django 5.2.1 on 2025-05-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_emergencyalert_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyalert',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
